# Generated by Django 4.1.4 on 2022-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0005_workorder_number_alter_product_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер'),
        ),
    ]
