services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: back_for_test-backend
    restart: unless-stopped
    volumes:
      - ../backend/:/app/backend/
      - static_volume:/app/backend/static/
      - media_volume:/app/backend/media/
    command: >
      sh -c "python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn back_for_test.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:1.25
    container_name: back_for_test-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
