# Generated by Django 4.1.4 on 2022-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
    ]
