# Generated by Django 4.1.4 on 2022-12-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nomenclature.nomenclature', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Наряд на производство',
                'verbose_name_plural': 'Наряды на производство',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10, verbose_name='Серийный номер')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Масса, кг.')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата производства')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='making.workorder')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
            },
        ),
    ]
