# Generated by Django 4.1.4 on 2022-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0002_rename_nomenclature_workorder_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
