# Generated by Django 4.1.4 on 2022-12-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_workorder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='number',
            field=models.CharField(default=1, max_length=5, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='making.workorder', verbose_name='Наряд'),
        ),
    ]
